name: SizeChange
version: '1.0-SNAPSHOT'
main: dev.anhuar.sizeChange.SizeChange
api-version: '1.21'
authors: [ anhuar dev, anhuar ruiz, myclass, 7Str1kes ]
description: Cosmetic plugin to resize the player
website: https://anhuar.dev